controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

get_order:
  path: /api/orders
  controller: App\Order\Action\GetOrdersAction
  methods: [ GET ]

add_order:
  path: /api/orders
  controller: App\Order\Action\CreateOrderAction
  methods: [ POST ]

edit_order:
  path: /api/orders/{orderId}
  controller: App\Order\Action\EditOrderAction
  methods: [ PATCH ]

delete_order:
  path: /api/orders/{orderId}
  controller: App\Order\Action\DeleteOrderAction
  methods: [ DELETE ]

orders_index:
  path: /tet
  controller: App\Controller\OrderController